name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - v4

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for git info
          token: ${{ secrets.TOKEN }}
          submodules: true

      - name: Checkout submodules
        run: git submodule update --init --recursive

      # 转换笔记结构
      - name: Transform
        run: rm -rf content/.obsidian content/Templates && mv content/*.md content/Atlas && find content/ -name "*.md" | xargs -I file  mv -f file content

      - uses: actions/setup-node@v3
        with:
          node-version: 18.14

      - name: Install Dependencies
        run: npm ci

      - name: Build Quartz
        run: npx quartz build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public
          publish_branch: master
          cname: wangze.tech
